- hosts: localhost
  tasks:
  - name: Create a k8s namespace
    k8s:
      name: bookinfo
      api_version: v1
      kind: Namespace
      state: present
  - name: Deploy bookinfo
    k8s:
      state: present
      namespace: bookinfo
      src: manifests/bookinfo.yaml
